//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpfPass
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordSet
    {
        public int SetId { get; set; }
        public string Location { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateChanged { get; set; }
        public string Status { get; set; }
        public int UserUserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
