//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpfPass
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.PasswordSets = new HashSet<PasswordSet>();
        }
    
        public int UserId { get; set; }
        public string Username { get; set; }
        public string MasterPassword { get; set; }
        public string Email { get; set; }
        public string Status { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual ICollection<PasswordSet> PasswordSets { get; set; }
    }
}
